Add admin.sol test codes
gobase/sbinft-contracts pull request #4
Opened 2022-07-05 21:54 UTC by mtbr-msys

2022-07-10 13:59 UTC, yuki-js approved these changes

2022-07-12 01:34 UTC, shinsuny commented on test/Admin.ts
> +      ).to.equal(true);
`AddressZero `がAdminとして追加されない方がいい。

2022-07-12 01:35 UTC, shinsuny commented on test/Admin.ts
> +    it("check adding zero address as admin", async function () {
Eventも発生されてることを追加する

2022-07-12 01:38 UTC, shinsuny commented on test/Admin.ts
> +      ).to.be.revertedWith("Admin:addAdmin newAdmin is the zero address");
文字："Admin:addAdmin newAdmin is the zero address" を`const`として指定して再利用する

2022-07-12 01:52 UTC, shinsuny requested changes
上記のコメントと`function batchAddAdmin`の名前は｀addAdmin｀に変更したいです。

よろしくお願いします。

2022-07-13 09:04 UTC, mtbr-msys commented on test/Admin.ts
> +      ).to.equal(true);
batchの中で_じゃないほうを呼び出すようにする

2022-07-13 09:06 UTC, mtbr-msys commented on test/Admin.ts
> +      ).to.equal(true);
internalの中で0x0のチェックをするようにする

2022-07-20 07:58 UTC, mtbr-msys commented
@shinsuny こちら遅くなりましたがご指摘の内容修正しましたので再度レビューお願いします。

2022-07-25 07:59 UTC, shinsuny approved these changes

2022-07-25 07:59 UTC, merged